// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ8gOOAD0cFp26yF08zL989E6sOL4E9no',
    appId: '1:535276098778:web:7ad40c1aba0d2d1282c1e3',
    messagingSenderId: '535276098778',
    projectId: 'jm-guide',
    authDomain: 'jm-guide.firebaseapp.com',
    storageBucket: 'jm-guide.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0aKksPpMB0rUM7Eo7gYhTYaTMh5Iw5Ok',
    appId: '1:535276098778:android:ff5614b5173a1f3c82c1e3',
    messagingSenderId: '535276098778',
    projectId: 'jm-guide',
    storageBucket: 'jm-guide.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1BvmwvUR1gJICc7vWn26JNzcCLbK6akc',
    appId: '1:535276098778:ios:c3abcece692fa53982c1e3',
    messagingSenderId: '535276098778',
    projectId: 'jm-guide',
    storageBucket: 'jm-guide.appspot.com',
    iosClientId: '535276098778-3djgk25p1bieep9i0iccrdp10unbutr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.guide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1BvmwvUR1gJICc7vWn26JNzcCLbK6akc',
    appId: '1:535276098778:ios:d9c4229a5bccfb9382c1e3',
    messagingSenderId: '535276098778',
    projectId: 'jm-guide',
    storageBucket: 'jm-guide.appspot.com',
    iosClientId: '535276098778-n76uumq5ui4ssu0mv6thrkfukkq5hsgk.apps.googleusercontent.com',
    iosBundleId: 'com.example.guide.RunnerTests',
  );
}
